Uploading jar built with Gradle.
Might fix https://github.com/TheTurkeyDev/Progression-Tweaks/issues/2
New build with the fix implemented was never provided, though a code change was done.

Possibly the above issue is causing this one https://git.magmafoundation.org/magmafoundation/Magma/-/issues/536
Will have to test later on server with magma and a firepit from progression tweaks (magmafoundation.org) to see if the code change fixed the issue.

SEO:
java.lang.NullPointerException: Exception in server tick loop
	at com.theprogrammingturkey.progressiontweaks.blocks.tileentities.TileFirePit$1.update(TileFirePit.java:46)